name: Build for GitHub Pages

on:
    push:
        branches: ["master"]

    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                yarn install
                yarn deploy
